# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180420_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('tid', models.IntegerField()),
                ('question', models.CharField(max_length=2000)),
                ('answer', models.TextField()),
                ('comments', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.IntegerField()),
                ('flag', models.BooleanField()),
            ],
        ),
    ]
