# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_questionbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbase',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionbase',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionbase',
            name='sid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionbase',
            name='tid',
            field=models.IntegerField(null=True),
        ),
    ]
