# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180420_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbase',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
